# Generated by Django 3.2.7 on 2021-11-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211110_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
