# Generated by Django 3.2.7 on 2021-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211111_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(default='https://www.kenyons.com/wp-content/uploads/2017/04/default-image-620x600.jpg'),
        ),
    ]
