# Generated by Django 3.2.9 on 2021-11-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211115_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='auctions.Category'),
        ),
    ]
