# Generated by Django 3.2.9 on 2021-11-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='category',
            new_name='categories',
        ),
    ]
