# Generated by Django 3.2.9 on 2021-11-22 22:17

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211122_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
    ]
